// src/components/CellButton.tsx
import { ParentProps } from "solid-js";

interface CellButtonProps extends ParentProps {
  hoverable?: boolean;
  disabled?: boolean;
  onClick?: VoidFunction;
}

export const CellButton = ({
  children,
  hoverable = true,
  ...props
}: CellButtonProps) => {
  return (
    <button
      class="cell"
      classList={{
        hoverable,
      }}
      {...props}
    >
      {children}
    </button>
  );
};

// src/components/CellButton.vue
<script setup>
const { hoverable, disabled } = defineProps({
    disabled: Boolean,
    hoverable: { type: Boolean, default: true },
})

const emit = defineEmits(['click'])

</script>

<template>
    <button class="cell" :class="{ hoverable }" :disabled="disabled" @click="emit('click')">
        <slot />
    </button>
</template>
