// src/pages/TodoForm.vue
<script setup>
import Cell from '../components/Cell.vue'
import CellButton from '../components/CellButton.vue'
import View from '../components/View.vue'
import { useRoute, useRouter } from 'vue-router'
import { inject, ref, computed } from 'vue'

const { query: { edit } } = useRoute()
const { back } = useRouter()
const store = inject('store', {})

const todo = store.todos?.[edit]
const description = ref(todo?.description ?? '')
const title = ref(todo?.title ?? '')
const disabled = computed(() => !description.value || !title.value)

const submit = () => {
    if (todo) store.editTodo({
        ...todo,
        description: description.value,
        title: title.value,
    })
    else store.addTodo(title.value, description.value)
    back()
}
</script>

<template>
    <View :items-count="4">
        <Cell header>{{ todo ? `ID: ${todo.id}` : "New" }}</Cell>
        <input placeholder="title" class="hoverable cell" v-model="title">
        <input placeholder="description" class="hoverable cell" v-model="description">
        <CellButton :disabled="disabled" @click="submit">
            {{ todo ? "Edit" : "Create" }}
        </CellButton>
    </View>
</template>

// solid_src/pages/TodoForm.tsx
import { useNavigate, useSearchParams } from "@solidjs/router";
import { Cell, CellButton, Input, View } from "../components";
import { createMemo, createSignal } from "solid-js";
import { globalStore } from "../store";

export const TodoForm = () => {
  const [{ edit }] = useSearchParams();
  const navigate = useNavigate();

  const todo = () => globalStore.todos()[parseInt(edit)];

  const [title, setTitle] = createSignal(todo()?.title || "");
  const [description, setDescription] = createSignal(todo()?.description || "");

  const submit = () => {
    const res = {
      ...(todo() || {}),
      description: description(),
      title: title(),
    };
    res.id ? globalStore.editTodo(res) : globalStore.addTodo(res);
    navigate(-1);
  };

  const disabled = createMemo(() => !title() || !description());

  return (
    <View>
      <Cell header>{todo() ? `ID: ${todo().id}` : "New"}</Cell>
      <Input
        value={title()}
        onChange={({ target: { value } }) => setTitle(value)}
      />
      <Input
        value={description()}
        onChange={({ target: { value } }) => setDescription(value)}
      />
      <CellButton disabled={disabled()} onClick={submit}>
        {todo() ? "Edit" : "Create"}
      </CellButton>
    </View>
  );
};
